### ISSUE TITLE
Wrong comment syntax

### ISSUE THREAD

**Issue by AAGaming00** [juliencombattelli/vscode-android-init-language-syntax#1]
https://github.com/juliencombattelli/vscode-android-init-language-syntax/blob/033cdfa969703f4ea137f400e53fa5f8b4750e00/language-configuration.json#L4

TMK android init language uses # for comments

**Comment by juliencombattelli** [comment]
Hi, thanks for the feedback. The issue is now fixed in version 0.4.0.

**Comment by AAGaming00** [comment]
Thanks!
